minVersion: 0.24.0
changelogPolicy: auto
targets:
  - name: symbol-collector
    includeNames: /libsentry(-android)?\.so/
    batchType: android
    bundleIdPrefix: sentry-unity-android-ndk-
  - name: upm
    releaseRepoOwner: getsentry
    releaseRepoName: unity
  - name: github
  - name: registry
    sdks:
      upm:sentry-unity:
