minVersion: 0.24.0
changelogPolicy: none
targets:
  - name: upm
    releaseRepoOwner: getsentry
    releaseRepoName: unity
  - name: github
    excludeNames: /^libsentry.*\.so$/
  - name: registry
    sdks:
      upm:sentry-unity:
