name: 🐞 Bug Report
description: Report a bug in this repo
labels: ["Unity", "Bug"]
body:
  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      placeholder: e.g. 4.0.0
    validations:
      required: true

  - type: input
    id: unity-version
    attributes:
      label: Unity Version
      placeholder: e.g. 2022.3.70f1
    validations:
      required: true

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      options:
        - label: Editor
        - label: Mobile (Android, iOS)
        - label: Desktop (Windows, macOS, Linux)
        - label: WebGL
        - label: Console

  - type: dropdown
    id: sentry-environment
    attributes:
      label: Sentry Environment
      options:
        - Sentry SaaS (sentry.io)
        - Self-hosted
    validations:
      required: true

  - type: dropdown
    id: other_error_monitoring
    attributes:
      description: Are you using any other error monitoring solution alongside Sentry?
      label: Other Error Monitoring Solution
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. What
        2. you
        3. did.
    validations:
      required: true

  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs Actual Result
      placeholder: |
        Expected: ...
        Actual: ...

        Include any logs, screenshots, or recordings if available.
    validations:
      required: true
