using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Sentry.Extensibility;
using Sentry.Unity.Integrations;
using UnityEditor;

namespace Sentry.Unity.Editor.Android;

internal class DebugSymbolUpload
{
    private readonly IDiagnosticLogger _logger;

    internal const string RelativeBuildOutputPathOld = "Temp/StagingArea/symbols";
    internal const string RelativeGradlePathOld = "Temp/gradleOut";
    internal const string RelativeBuildOutputPathNew = "Library/Bee/artifacts/Android";
    internal const string RelativeAndroidPathNew = "Library/Bee/Android";

    internal const string SymbolUploadLogName = "sentry-symbols-upload.log";
    internal const string MappingUploadLogName = "sentry-mapping-upload.log";

    private readonly string _unityProjectPath;
    private readonly string _gradleProjectPath;
    private readonly string _gradleScriptPath;
    private readonly bool _isExporting;
    private readonly bool _isMinifyEnabled;

    private readonly SentryCliOptions? _cliOptions;
    private readonly List<string> _symbolUploadPaths;
    private readonly string _mappingFilePath;

    internal const string SymbolUploadTaskStartComment = "// Autogenerated Sentry symbol upload task [start]";
    internal const string SymbolUploadTaskEndComment = "// Autogenerated Sentry symbol upload task [end]";
    private const string SentryCliMarker = "SENTRY_CLI";
    private const string UploadArgsMarker = "UPLOAD_ARGS";
    private const string ProguardArgsMarker = "PROGUARD_ARGS";

    private const string RaiseIssuePrompt = "\nPlease raise an issue over at https://github.com/getsentry/sentry-unity/issues";

    private string SymbolUploadTaskFormat
    {
        get
        {
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// Credentials and project settings information are stored in the sentry.properties file");
            stringBuilder.AppendLine("afterEvaluate {");
            stringBuilder.AppendLine("task sentryUploadSymbols {");
            stringBuilder.AppendLine("    doLast {");
            stringBuilder.AppendLine("        println 'Uploading symbols to Sentry.'");

            var logsDir = $"{ConvertSlashes(_unityProjectPath)}/Logs";
            Directory.CreateDirectory(logsDir);
            stringBuilder.AppendLine($"        def logFilePath = '{logsDir}/{SymbolUploadLogName}'");
            stringBuilder.AppendLine("        def sentryLogFile = new FileOutputStream(logFilePath)");
            stringBuilder.AppendLine("        def outputStream = new org.apache.tools.ant.util.TeeOutputStream(System.out, sentryLogFile)");
            stringBuilder.AppendLine("        def errorStream = new org.apache.tools.ant.util.TeeOutputStream(System.err, sentryLogFile)");

            stringBuilder.AppendLine("        exec {");
            stringBuilder.AppendLine("            environment 'SENTRY_PROPERTIES', './sentry.properties'");
            stringBuilder.AppendLine($"            executable '{SentryCliMarker}'");
            stringBuilder.AppendLine($"            args = ['debug-files', 'upload'{UploadArgsMarker}]");
            if (!_isExporting)
            {
                stringBuilder.AppendLine("            standardOutput outputStream");
                stringBuilder.AppendLine("            errorOutput errorStream");
            }
            stringBuilder.AppendLine("        }");

            CheckMapping(stringBuilder);
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");
            stringBuilder.AppendLine(string.Empty);
            stringBuilder.AppendLine("tasks.assembleDebug.finalizedBy sentryUploadSymbols");
            stringBuilder.AppendLine("tasks.assembleRelease.finalizedBy sentryUploadSymbols");
            stringBuilder.AppendLine("tasks.bundleDebug.finalizedBy sentryUploadSymbols");
            stringBuilder.AppendLine("tasks.bundleRelease.finalizedBy sentryUploadSymbols");

            stringBuilder.AppendLine("}");
            return stringBuilder.ToString();
        }
    }

    public DebugSymbolUpload(IDiagnosticLogger logger,
        SentryCliOptions? cliOptions,
        string unityProjectPath,
        string gradleProjectPath,
        bool isExporting = false,
        bool minifyEnabled = false,
        IApplication? application = null)
    {
        _logger = logger;

        _unityProjectPath = unityProjectPath;
        _gradleProjectPath = gradleProjectPath;
        _gradleScriptPath = Path.Combine(_gradleProjectPath, "launcher/build.gradle");
        _isExporting = isExporting;
        _isMinifyEnabled = minifyEnabled;

        _cliOptions = cliOptions;
        _symbolUploadPaths = GetSymbolUploadPaths(application);
        _mappingFilePath = GetMappingFilePath(application);
    }

    public void AppendUploadToGradleFile(string sentryCliPath)
    {
        _logger.LogInfo("Appending debug symbols upload task to gradle file.");

        sentryCliPath = ConvertSlashes(sentryCliPath);
        if (!File.Exists(sentryCliPath))
        {
            throw new FileNotFoundException($"Failed to find sentry-cli{RaiseIssuePrompt}", sentryCliPath);
        }

        var uploadDifArguments = ", '--il2cpp-mapping'";
        if (_cliOptions?.UploadSources == true)
        {
            uploadDifArguments += ", '--include-sources'";
        }

        if (_cliOptions?.IgnoreCliErrors == true)
        {
            uploadDifArguments += ", '--allow-failure'";
        }

        if (_isExporting)
        {
            _logger.LogInfo("Project is exporting. Setting upload-dif to 'project.rootDir'");

            uploadDifArguments += ", project.rootDir";
            sentryCliPath = $"./{Path.GetFileName(sentryCliPath)}";
        }
        else if (_symbolUploadPaths.Count > 0)
        {
            _logger.LogInfo("Setting upload-dif paths");

            foreach (var symbolUploadPath in _symbolUploadPaths)
            {
                if (Directory.Exists(symbolUploadPath))
                {
                    _logger.LogDebug("Adding '{0}'", symbolUploadPath);
                    uploadDifArguments += $", '{ConvertSlashes(symbolUploadPath)}'";
                }
                else
                {
                    throw new DirectoryNotFoundException($"Failed to find the symbols directory at {symbolUploadPath}{RaiseIssuePrompt}");
                }
            }
        }

        var uploadProguardArguments = string.Empty;
        if (_cliOptions?.IgnoreCliErrors == true)
        {
            uploadProguardArguments += ", '--allow-failure'";
        }

        uploadProguardArguments += $", '{_mappingFilePath}'";

        var symbolUploadText = SymbolUploadTaskFormat;
        symbolUploadText = symbolUploadText.Trim();
        symbolUploadText = symbolUploadText.Replace(SentryCliMarker, sentryCliPath);
        symbolUploadText = symbolUploadText.Replace(UploadArgsMarker, uploadDifArguments);
        symbolUploadText = symbolUploadText.Replace(ProguardArgsMarker, uploadProguardArguments);

        var gradleBuildFile = LoadGradleScript();
        if (gradleBuildFile.Contains(SymbolUploadTaskStartComment) || gradleBuildFile.Contains("task sentryUploadSymbols"))
        {
            throw new InvalidOperationException($"Failed to create Debug Symbol Upload Task. Task already exists in gradle file. A clean build should resolve this.{RaiseIssuePrompt}");
        }

        var stringBuilder = new StringBuilder(gradleBuildFile);
        stringBuilder.AppendLine(SymbolUploadTaskStartComment);
        stringBuilder.AppendLine(symbolUploadText);
        stringBuilder.AppendLine(SymbolUploadTaskEndComment);
        File.WriteAllText(_gradleScriptPath, stringBuilder.ToString());
    }

    private string LoadGradleScript()
    {
        if (!File.Exists(_gradleScriptPath))
        {
            throw new FileNotFoundException($"Failed to find the gradle config.{RaiseIssuePrompt}", _gradleScriptPath);
        }

        return File.ReadAllText(_gradleScriptPath);
    }

    public void RemoveUploadFromGradleFile()
    {
        _logger.LogDebug("Attempting to remove the previous upload task from the gradle project.");
        var gradleBuildFile = LoadGradleScript();
        if (!gradleBuildFile.Contains(SymbolUploadTaskStartComment))
        {
            _logger.LogDebug("No previous upload task found.");
            return;
        }

        var pattern = Regex.Escape(SymbolUploadTaskStartComment) + ".*?" + Regex.Escape(SymbolUploadTaskEndComment);
        var regex = new Regex(pattern, RegexOptions.Singleline);
        gradleBuildFile = regex.Replace(gradleBuildFile, "");

        if (gradleBuildFile.Contains(SymbolUploadTaskStartComment) ||
            gradleBuildFile.Contains("task sentryUploadSymbols") ||
            gradleBuildFile.Contains(SymbolUploadTaskEndComment))
        {
            throw new InvalidOperationException($"Failed to remove Debug Symbol Upload Task from gradle file. A clean build should resolve this.{RaiseIssuePrompt}");
        }

        using var streamWriter = File.CreateText(_gradleScriptPath);
        streamWriter.Write(gradleBuildFile);
    }

    public void TryCopySymbolsToGradleProject(IApplication? application = null)
    {
        if (!_isExporting)
        {
            return;
        }

        _logger.LogInfo("Copying debug symbols to exported gradle project.");
        var targetRoot = Path.Combine(_gradleProjectPath, "symbols");
        foreach (var symbolUploadPath in _symbolUploadPaths)
        {
            // Seems like not all paths exist all the time... e.g. Unity 2021.2.21 misses RelativeAndroidPathNew.
            if (!Directory.Exists(symbolUploadPath))
            {
                continue;
            }

            foreach (var sourcePath in Directory.GetFiles(symbolUploadPath, "*.so", SearchOption.AllDirectories))
            {
                var targetPath = sourcePath.Replace(symbolUploadPath, targetRoot);
                _logger.LogDebug("Copying '{0}' to '{1}'", sourcePath, targetPath);

                Directory.CreateDirectory(Path.GetDirectoryName(targetPath));
                File.Copy(sourcePath, targetPath, true);
            }
        }
    }

    internal List<string> GetSymbolUploadPaths(IApplication? application = null)
    {
        var paths = new List<string>();
        if (IsNewerThanUnity2021_2(application))
        {
            _logger.LogInfo("Unity version 2021.2 or newer detected. Root for symbols upload: 'Library'.");
            paths.Add(Path.Combine(_unityProjectPath, RelativeBuildOutputPathNew));
            paths.Add(Path.Combine(_unityProjectPath, RelativeAndroidPathNew));
        }
        else
        {
            _logger.LogInfo("Unity version 2021.1 or older detected. Root for symbols upload: 'Temp'.");
            paths.Add(Path.Combine(_unityProjectPath, RelativeBuildOutputPathOld));
            paths.Add(Path.Combine(_unityProjectPath, RelativeGradlePathOld));
        }

        return paths;
    }

    // Starting with Unity 2021.2 the build-process caches the build output inside 'Library' instead of 'Temp'
    internal static bool IsNewerThanUnity2021_2(IApplication? application = null) => SentryUnityVersion.IsNewerOrEqualThan("2021.2", application);

    // Gradle doesn't support backslashes on path (Windows) so converting to forward slashes
    internal static string ConvertSlashes(string path) => path.Replace(@"\", "/");

    private void CheckMapping(StringBuilder stringBuilder)
    {
        if (!_isMinifyEnabled)
            return;

        stringBuilder.AppendLine("        println 'Uploading mapping file to Sentry.'");
        if (!_isExporting)
        {
            var logsDir = $"{ConvertSlashes(_unityProjectPath)}/Logs";
            Directory.CreateDirectory(logsDir);
            stringBuilder.AppendLine($"        def mappingLogFilePath = '{logsDir}/{MappingUploadLogName}'");
            stringBuilder.AppendLine($"        def mappingLogFile = new FileOutputStream(mappingLogFilePath)");
            stringBuilder.AppendLine("        def mappingOutputStream = new org.apache.tools.ant.util.TeeOutputStream(System.out, mappingLogFile)");
            stringBuilder.AppendLine("        def mappingErrorStream = new org.apache.tools.ant.util.TeeOutputStream(System.err, mappingLogFile)");
        }
        stringBuilder.AppendLine("        exec {");
        stringBuilder.AppendLine("            environment 'SENTRY_PROPERTIES', './sentry.properties'");
        stringBuilder.AppendLine($"            executable '{SentryCliMarker}'");
        stringBuilder.AppendLine($"            args = ['upload-proguard'{ProguardArgsMarker}]");
        // stringBuilder.AppendLine($"            args = ['debug-files', 'upload'{UploadArgsMarker}]");
        if (!_isExporting)
        {
            stringBuilder.AppendLine("            standardOutput mappingOutputStream");
            stringBuilder.AppendLine("            errorOutput mappingErrorStream");
        }
        stringBuilder.AppendLine("        }");
    }

    private string GetMappingFilePath(IApplication? application)
    {
        var gradleRelativePath = IsNewerThanUnity2021_2(application)
            ? "Library/Bee/Android/Prj/IL2CPP/Gradle"
            : "Temp/gradleOut";

        string mappingPathFormat;
        var buildType = EditorUserBuildSettings.development ? "debug" : "release";
        if (_isExporting)
        {
            mappingPathFormat =
                "file(\"${rootDir}/launcher/build/outputs/mapping/{0}/mapping.txt\").absolutePath";
        }
        else
        {
            var gradleProjectPath = Path.Combine(_unityProjectPath, gradleRelativePath);
            mappingPathFormat = Path.Combine(gradleProjectPath, "launcher/build/outputs/mapping/{0}/mapping.txt");
        }

        var mappingPath = mappingPathFormat.Replace("{0}", buildType);
        // Make sure the slashes are uniform (and forward)
        return ConvertSlashes(mappingPath);
    }
}
