name: "CI"

on:
  push:
    branches:
      - main
      - release/*
      - fix/linux-6.5-line-numbers
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
  workflow_dispatch:

jobs:
  linux-il2cpp-diagnostics:
    name: Linux IL2CPP diagnostics
    uses: ./.github/workflows/linux-il2cpp-line-number-diagnostics.yml
    with:
      backend: native
      unitylinker-additional-args: --link-symbols
    secrets:
      UNITY_LICENSE_SERVER_CONFIG: ${{ secrets.UNITY_LICENSE_SERVER_CONFIG }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_TEST_DSN: ${{ secrets.SENTRY_TEST_DSN }}
