name: "IntegrationTest: Run iOS"
on:
  workflow_call:
    inputs:
      unity-version:
        required: true
        type: string
      ios-version:
        required: true
        type: string
      init-type:
        required: true
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      status:
        description: "Integration test status"
        value: ${{ jobs.run.outputs.status }}

defaults:
  run:
    shell: pwsh

jobs:
  run:
    name: ${{ inputs.unity-version }} ${{ inputs.ios-version }} ${{ inputs.init-type }}
    runs-on: macos-14 # Pinning to get the oldest, supported version of iOS simulator
    # Map the job outputs to step outputs
    outputs:
      status: ${{ steps.integration-test.outputs.status }}
    env:
      UNITY_VERSION: ${{ inputs.unity-version }}
      IOS_VERSION: ${{ inputs.ios-version }}
      INIT_TYPE: ${{ inputs.init-type }}
      ARTIFACTS_PATH: samples/IntegrationTest/test-artifacts/
      SENTRY_TEST_DSN: ${{ secrets.SENTRY_TEST_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Initialize app-runner submodule
        run: git submodule update --init modules/app-runner
        shell: bash

      - name: Initialize app-runner submodule
        run: git submodule update --init modules/app-runner
        shell: bash

      - name: Download app artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: testapp-ios-compiled-${{ env.UNITY_VERSION }}-${{ env.INIT_TYPE }}
          path: samples/IntegrationTest/Build

      - name: List downloaded files
        run: |
          Get-ChildItem -Path "samples/IntegrationTest/Build" -Recurse

      - name: Set Xcode for iOS version ${{ env.IOS_VERSION }}
        if: ${{ env.IOS_VERSION != 'latest'}}
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # pin@v1.6
        with:
          xcode-version: '15.0' # to run iOS 17.0 we need Xcode 15.0

      - name: Run iOS Integration Tests
        id: integration-test
        timeout-minutes: 20
        run: |
          $env:SENTRY_TEST_APP = "samples/IntegrationTest/Build/IntegrationTest.app"
          $env:SENTRY_IOS_VERSION = "${{ inputs.ios-version }}"
          Invoke-Pester -Path test/IntegrationTest/Integration.Tests.iOS.ps1 -CI
          echo "status=success" >> $env:GITHUB_OUTPUT

      - name: Upload test results on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: testapp-ios-logs-${{ env.IOS_VERSION }}-${{ env.UNITY_VERSION }}-${{ env.INIT_TYPE }}
          path: |
            ${{ env.ARTIFACTS_PATH }}
            test/IntegrationTest/results/
          retention-days: 14
