name: "IntegrationTest: Run Linux"
on:
  workflow_call:
    inputs:
      unity-version:
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  run:
    name: Linux ${{ inputs.unity-version }}
    runs-on: ubuntu-latest
    env:
      SENTRY_TEST_DSN: ${{ secrets.SENTRY_TEST_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Initialize app-runner submodule
        run: git submodule update --init modules/app-runner
        shell: bash

      - name: Download test app artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: testapp-desktop-compiled-${{ inputs.unity-version }}-linux

      - name: Extract test app
        run: tar -xvzf test-app-desktop.tar.gz

      - name: Set executable permission
        run: chmod +x samples/IntegrationTest/Build/test
        shell: bash

      - name: Run Integration Tests
        timeout-minutes: 20
        run: |
          xvfb-run pwsh -Command '
            $env:SENTRY_TEST_APP = "samples/IntegrationTest/Build/test";
            Invoke-Pester -Path test/IntegrationTest/Integration.Tests.Desktop.ps1 -CI'
        shell: bash

      - name: Upload test results on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: testapp-desktop-logs-linux-${{ inputs.unity-version }}
          path: |
            test/IntegrationTest/results/
          retention-days: 14
